### PR TITLE
Make link open in new tab

### PR DESCRIPTION
**Pull request by MaterArc**

### CODE REVIEW

**Comment by griffpatch** [comment]
Thanks, merged

**Comment by ColdFire69** [comment]
> Thanks, merged

@griffpatch I got banned on Scratch but I would like to say can you check out my Scratch profile called Riel101?

**Comment by MaterArc** [comment]
> > Thanks, merged
> 
> @griffpatch I got banned on Scratch but I would like to say can you check out my Scratch profile called Riel101?

Please don't advertise, especially not on Github or a merged pr, either.

**Comment by MarioBonus** [comment]
@MaterArc -_-

**Comment by MarioBonus** [comment]
> > > Thanks, merged
> > 
> > 
> > @griffpatch I got banned on Scratch but I would like to say can you check out my Scratch profile called Riel101?
> 
> Please don't advertise, especially not on Github or a merged pr, either.

@MaterArc I was ASKING

**Comment by ColdFire69** [comment]
> > > Thanks, merged
> > 
> > 
> > @griffpatch I got banned on Scratch but I would like to say can you check out my Scratch profile called Riel101?
> 
> Please don't advertise, especially not on Github or a merged pr, either.

@MaterArc Sorry but I think you misunderstood my message. I was wanting to ask but I think you got it the other way around.

**Comment by ColdFire69** [comment]
> > > Thanks, merged
> > 
> > 
> > @griffpatch I got banned on Scratch but I would like to say can you check out my Scratch profile called Riel101?
> 
> Please don't advertise, especially not on Github or a merged pr, either.

@MaterArc You are correct, but I was asking because I want more people to get to know me.

**Pull request merged**
